### ISSUE TITLE
Flipped image card, always show White POV

### ISSUE THREAD

**Issue by Deleplace** [gregsramblings/chessmsgs#9]
## Steps

- As White: make a move
- Share the new URL with your opponent

## Expected

The image card (as displayed by Whatsapp or Twitter or other) should show the board from the point of view of the Black

## Observed

The image card shows the board from the point of view of the White

## How to fix

I suspect that the image card generation currently only takes the state of the board into account, but doesn't take into account who was the last player. Ideally, the generated image should be tailored for **the next player** (the one who will have to read the board and make the next move).

**Comment by Deleplace** [comment]
I discovered this while testing #8. I have not thoroughly tested all possible combinations of {last player color} x {Copy or Share} x {target service that displays a card}.

If you can reproduce my observation and agree with the intent, then let's fix it!

**Comment by gregsramblings** [comment]
Works on my machine LOL

The FEN (in URL) indicates whose's move it is and orients the board accordingly in the preview. Are you not seeing that?

**Comment by gregsramblings** [comment]
The FEN (board position in the URL) shows who's move it is. I just never got around to changing the code to flip the board. One way to approach it is to rewrite the FEN to reverse the board.  Any ideas? Lots of string manipulation.

**Comment by gregsramblings** [comment]
I implemented this - check it out :) 

I'll highlight the last move soon (I noticed a pull request in chess-image-generator that implements this in the lib)

**Comment by Deleplace** [comment]
It works!

And yes, showing the last move in the card image would be awesome.

**Comment by gregsramblings** [comment]
Done - check it out :)
